"""
Copy various data from the HPC cluster to the local machine.

It supports copying the following:

- the correct `rev<revision>_<region>_*_mfa.tgz` archive that is needed to
  run the REMIND-MFA.
- the recent `rev<revision>_*_remind.tgz` archive that contains the data generated by
  `mrindustry`.
- all `source` data that is needed to run `mrmfa`.
"""

import csv
import os
import re
import shlex
import subprocess
import urllib.error
import urllib.request
from pathlib import Path
from typing import Annotated

import typer
from dotenv import load_dotenv

from remind_mfa.common.cli import prompt_for_config_names
from remind_mfa.common.common_config import InputCfg
from remind_mfa.common.common_data_reader import CommonDataReader
from remind_mfa.common.config_loader import load_config

app = typer.Typer(add_completion=False)

DEFAULT_REMOTE_REPOSITORY = Path("/p/projects/rd3mod/inputdata")
DEFAULT_ARCHIVE_DIRECTORY = DEFAULT_REMOTE_REPOSITORY / "output"
SOURCE_LIST = Path(__file__).resolve().parents[1] / "docs" / "mrmfa_sources.csv"


def read_input_cfg(config_names: list[str]) -> InputCfg:
    config = load_config(config_names)

    if "input" not in config:
        raise ValueError(
            f"Configuration {', '.join(config_names)} does not contain an 'input' section."
        )

    return InputCfg.model_validate(config["input"])


def resolve_destination_path(input_cfg: InputCfg) -> Path:
    destination_path = Path(input_cfg.resolved_madrat_output_path).expanduser()
    destination_path.mkdir(parents=True, exist_ok=True)
    return destination_path


def get_archive_destination(config_names: list[str] | None) -> Path:
    if not config_names:
        config_names = prompt_for_config_names()
    return resolve_destination_path(read_input_cfg(config_names))


def find_remote_archive(
    remote_host: str,
    remote_dir: Path,
    pattern: str,
    *,
    pick_first_if_multiple: bool = False,
    archive_kind: str = "archive",
) -> str:
    remote_command = (
        "find "
        f"{shlex.quote(str(remote_dir))} "
        "-maxdepth 1 -type f "
        f"-name {shlex.quote(pattern)} -print"
    )
    result = subprocess.run(
        ["ssh", remote_host, remote_command],
        capture_output=True,
        text=True,
        check=False,
    )

    if result.returncode != 0:
        stderr = result.stderr.strip() or "unknown ssh error"
        raise RuntimeError(f"Failed to query remote archives on {remote_host}: {stderr}")

    matches = sorted({line.strip() for line in result.stdout.splitlines() if line.strip()})
    if not matches:
        raise FileNotFoundError(
            f"No matching tgz archive found in {remote_host}:{remote_dir} for pattern '{pattern}'."
        )
    if len(matches) > 1:
        if pick_first_if_multiple:
            print(
                f"Warning: Multiple matching {archive_kind} tgz archives found. "
                f"Using first match: {matches[0]}. All matches: {matches}"
            )
            return matches[0]
        raise ValueError(
            "Multiple matching tgz archives found for the selected revision/region mapping. "
            f"Matches: {matches}"
        )
    return matches[0]


def fetch_remind_cfg() -> str:
    url = "https://raw.githubusercontent.com/remindmodel/pre-processing/refs/heads/master/config/default.cfg"
    try:
        with urllib.request.urlopen(url, timeout=15) as response:
            return response.read().decode("utf-8")
    except urllib.error.URLError as exc:
        raise RuntimeError(f"Failed to fetch REMIND config from {url}: {exc}") from exc


def parse_revision_from_default_cfg(cfg_text: str) -> str:
    match = re.search(
        r'^\s*cfg\$revision\s*<-\s*"([^"]+)"\s*$',
        cfg_text,
        flags=re.MULTILINE,
    )
    if not match:
        raise ValueError("Could not find cfg$revision in REMIND default.cfg.")
    return match.group(1).strip()


def resolve_remind_revision(remind_revision_override: str | None) -> str:
    if remind_revision_override:
        return remind_revision_override.strip()

    cfg_text = fetch_remind_cfg()
    return parse_revision_from_default_cfg(cfg_text)


def build_remind_tgz_pattern(remind_revision: str) -> str:
    return f"rev{remind_revision}_*_remind.tgz"


def copy_archive(remote_host: str, remote_archive_path: str, destination_dir: Path) -> None:
    subprocess.run(
        ["scp", f"{remote_host}:{remote_archive_path}", str(destination_dir)],
        check=True,
    )


def read_sources(source_list: Path) -> list[str]:
    """Read unique source directory names from the mrmfa source list."""
    sources: list[str] = []
    with source_list.open(encoding="utf-8", newline="") as source_file:
        for row in csv.DictReader(source_file):
            for source in row["Source"].split(","):
                source = source.strip()
                if not source:
                    continue
                if Path(source).name != source or source in {".", ".."}:
                    raise ValueError(f"Invalid source name in {source_list}: {source!r}")
                if source not in sources:
                    sources.append(source)
    return sources


def copy_files(remote_files: list[str], destination_dir: Path, dry_run: bool) -> None:
    if not dry_run:
        destination_dir.mkdir(parents=True, exist_ok=True)

    rsync_command = [
        "rsync",
        "-avzh",
        "--progress",
        "--inplace",
        *(("--dry-run",) if dry_run else ()),
        "--exclude",
        ".git",
        "--exclude",
        ".Rhistory",
        "--exclude",
        ".venv",
        *remote_files,
        str(destination_dir),
    ]
    subprocess.run(rsync_command, check=True)


def copy_sources(
    remote_host: str,
    sources: list[str],
    source_repository: Path,
    destination_dir: Path,
    dry_run: bool,
) -> None:
    copy_files(
        [f"{remote_host}:{source_repository}/{source}" for source in sources],
        destination_dir,
        dry_run,
    )


def verify_remote_sources(remote_host: str, sources: list[str], source_repository: Path) -> None:
    """Verify that all required source directories (as specified via `sources`) exist on the remote host."""
    try:
        result = subprocess.run(
            [
                "ssh",
                remote_host,
                "find",
                str(source_repository),
                "-mindepth",
                "1",
                "-maxdepth",
                "1",
                "-type",
                "d",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
    except FileNotFoundError as error:
        raise RuntimeError("ssh executable was not found.") from error
    except subprocess.CalledProcessError as error:
        raise RuntimeError(
            f"Source repository is unavailable on {remote_host}: {source_repository}"
        ) from error

    available_sources = {Path(line).name for line in result.stdout.splitlines()}
    missing_sources = [source for source in sources if source not in available_sources]
    if missing_sources:
        raise RuntimeError(f"Missing source directories: {', '.join(missing_sources)}")


def copy_mappings(
    remote_host: str, destination_dir: Path, mappings_repository: Path, dry_run: bool
) -> None:
    copy_files(
        [f"{remote_host}:{mappings_repository}/"],
        destination_dir,
        dry_run,
    )


@app.command("mfa-archive")
def copy_mfa_archive(
    remote_host: str = typer.Argument(
        ..., help="Remote SSH target, for example user@host or an SSH config host alias."
    ),
    remote_dir: Annotated[
        Path,
        typer.Option(
            "--remote-dir",
            help="Remote directory that contains the MFA archives.",
        ),
    ] = DEFAULT_ARCHIVE_DIRECTORY,
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Print the selected source and destination without running scp."
    ),
    config_names: Annotated[
        list[str] | None,
        typer.Option(
            "--config",
            help="Configuration name under config/. Repeat to stack configurations.",
        ),
    ] = None,
) -> None:
    """Copy the config-selected MFA archive."""
    if not config_names:
        config_names = prompt_for_config_names()
    input_cfg = read_input_cfg(config_names)
    destination_dir = resolve_destination_path(input_cfg)
    mfa_pattern = CommonDataReader.build_target_tgz_pattern(
        input_cfg.input_data_revision, input_cfg.region_mapping
    )
    typer.echo(f"Looking for MFA archive on {remote_host}:{remote_dir}")
    mfa_remote_archive_path = find_remote_archive(remote_host, remote_dir, mfa_pattern)
    typer.echo(f"Selected MFA archive: {mfa_remote_archive_path}")
    typer.echo(f"Destination directory: {destination_dir}")
    if dry_run:
        return
    copy_archive(remote_host, mfa_remote_archive_path, destination_dir)
    typer.echo("Archive copy completed.")


@app.command("remind-archive")
def copy_remind_archive(
    remote_host: str = typer.Argument(
        ..., help="Remote SSH target, for example user@host or an SSH config host alias."
    ),
    remote_dir: Annotated[
        Path,
        typer.Option("--remote-dir", help="Remote directory that contains REMIND archives."),
    ] = DEFAULT_ARCHIVE_DIRECTORY,
    remind_revision: Annotated[
        str | None,
        typer.Option(
            "--remind-revision", help="Manual revision override; skips fetching default.cfg."
        ),
    ] = None,
    dry_run: bool = typer.Option(
        False, "--dry-run", help="Print the selected source and destination without running scp."
    ),
    config_names: Annotated[
        list[str] | None,
        typer.Option(
            "--config", help="Configuration name under config/. Repeat to stack configurations."
        ),
    ] = None,
) -> None:
    """Copy the most recent REMIND archive generated by mrindustry."""
    destination_dir = get_archive_destination(config_names)
    typer.echo("Fetching latest REMIND revision...")
    revision = resolve_remind_revision(remind_revision)
    typer.echo(f"Resolved REMIND revision: {revision}")
    typer.echo(f"Looking for REMIND archive on {remote_host}:{remote_dir}")
    remote_archive_path = find_remote_archive(
        remote_host,
        remote_dir,
        build_remind_tgz_pattern(revision),
        pick_first_if_multiple=True,
        archive_kind="REMIND",
    )
    typer.echo(f"Selected REMIND archive: {remote_archive_path}")
    typer.echo(f"Destination directory: {destination_dir}")
    if dry_run:
        return
    copy_archive(remote_host, remote_archive_path, destination_dir)
    typer.echo("Archive copy completed.")


@app.command("mrmfa-sources")
def copy_mrmfa_sources(
    remote_host: str = typer.Argument(
        ..., help="SSH target where the mrmfa source repository is available."
    ),
    remote_dir: Annotated[
        Path,
        typer.Option("--remote-dir", help="Remote directory that contains mrmfa sources."),
    ] = DEFAULT_REMOTE_REPOSITORY,
    dry_run: bool = typer.Option(
        False, "--dry-run", help="List the source and mapping transfers without copying."
    ),
) -> None:
    """Copy mrmfa sources and mappings into `MADRAT_MAINFOLDER`."""
    madrat_mainfolder = os.getenv("MADRAT_MAINFOLDER")
    if not madrat_mainfolder:
        raise typer.BadParameter("MADRAT_MAINFOLDER is not set.")
    madrat_main = Path(madrat_mainfolder).expanduser().resolve()
    if not madrat_main.is_dir():
        raise typer.BadParameter(f"MADRAT_MAINFOLDER is not a directory: {madrat_main}")
    source_dir = remote_dir / "sources"
    mappings_dir = remote_dir / "mappings"

    sources = read_sources(SOURCE_LIST)
    typer.echo(f"Found {len(sources)} sources in {SOURCE_LIST}")
    typer.echo(f"Checking sources on {remote_host}")
    verify_remote_sources(remote_host, sources, source_dir)
    try:
        typer.echo(f"Copying sources to {madrat_main / 'sources'}")
        copy_sources(remote_host, sources, source_dir, madrat_main / "sources", dry_run)
        typer.echo(f"Copying mappings to {madrat_main / 'mappings'}")
        copy_mappings(remote_host, madrat_main / "mappings", mappings_dir, dry_run)
    except KeyboardInterrupt:
        typer.echo("Transfer interrupted.", err=True)
        raise typer.Exit(130) from None


if __name__ == "__main__":
    load_dotenv()

    app()
